import os

CLOUDCUBE_ACCESS_KEY_ID = os.getenv('CLOUDCUBE_ACCESS_KEY_ID')
CLOUDCUBE_SECRET_ACCESS_KEY = os.getenv('CLOUDCUBE_SECRET_ACCESS_KEY')
TELEGRAM_API_TOKEN = os.getenv('TELEGRAM_API_TOKEN')
CLOUDCUBE_URL = os.getenv('CLOUDCUBE_URL')
DATABASE_URL = os.getenv('DATABASE_URL')
